title: Anisul Islam 
description: ğŸš€ Software Developer| ğŸ§‘ğŸ¾â€ğŸ’» Remote-Ready Tech Expert| ğŸ¤– AI & Machine Learning Enthusiast
WebDescription: ğŸš€ Experienced Software Developer | ğŸ¤– AI & Machine Learning Enthusiast | Java, Python, JS, C | Team Leader | ğŸ§‘ğŸ¾â€ğŸ’» Remote-Ready Tech Expert 
# show_downloads: false
# google_analytics:
theme: jekyll-theme-hacker
linkedin:
  profile_url: https://www.linkedin.com/in/whoisanis
github:
  profile_url: https://github.com/anisul-islam-prog
  whereisanis: https://github.com/anisul-islam-prog/whereisanis
  dsvtojson: https://github.com/anisul-islam-prog/dsvtojson
  stlf: https://github.com/anisul-islam-prog/STLFusingMLAlgorithms
  eticket: https://github.com/anisul-islam-prog/e-ticketforbus
  sbchatapp: https://github.com/anisul-islam-prog/spring-boot-chatapp 
  sellize: https://github.com/anisul-islam-prog/sellize
leetcode:
  profile_url: https://leetcode.com/u/lordofxtreme/
author: Anisul Islam